apiVersion: v2
name: lucidity-test
description: A Helm chart for Hello App Kubernetes
type: application
version: 0.1.4
appVersion: "1.16.0"
maintainers:
  - name: "Mallikarjuna"
    email: "mallikatjuna.kukati20@gmail.com"
