apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/Mallikarjuna18/githubactioncheck.git
      targetRevision: main
      path: k8Deployfiles/namespace

    - repoURL: https://github.com/Mallikarjuna18/githubactioncheck.git
      targetRevision: main
      path: k8Deployfiles/helloWorld-helm

  destination:
    server: https://kubernetes.default.svc
    namespace: lucidity

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
