name: Build Application
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image
      run: |
        docker build -t mallikarjuna18/hello-world:${{ github.sha }} ./app
    - name: Push Docker Image
      run: |
        docker push mallikarjuna18/hello-world:${{ github.sha }}
