name: Build Application
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set Image Tag
      run: |
        echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Build Docker Image
      run: |
        docker build -t malli183/helloworld:${IMAGE_TAG} ./app
    - name: Push Docker Image
      run: |
        docker push malli183/helloworld:${IMAGE_TAG}
