name: infra-deploy

on:
  push:
    branches:
      - main
    paths:
      - "*.tf"
      - "*.tfvars"
      - "terraform/**"
      - "helm/*"
  workflow_dispatch:
jobs:
  terraform:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Terrafrom init and plan
        run: |
          terraform init
          terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve
      - name: Repo addition to Helm Dependencies
        run: |
          chmod +x helm/addRepos.sh
          ./helm/addRepos.sh
      - name: Build Helm Dependencies
        run: |
          chmod +x helm/dependencyBuild.sh
          ./helm/dependencyBuild.sh
      - name: Install Platform Components
        run: |
          chmod +x helm/install.sh
          ./helm/install.sh
